### ISSUE TITLE
problem with casing change for ngerman

### ISSUE THREAD

**Issue by u-fischer** [latex3/babel#321] opened 2024-11-25 18:59 UTC
I wanted to demonstrate the change of the casing to eszett for german. With traditional german it works with (and without) ldf-files without problems:

~~~~
\documentclass[]{article}
\usepackage[german]{babel}
\babelprovide[casing=eszett]{german} 
\usepackage{fontspec}
\setmainfont{dejavusans}
\begin{document}
\MakeUppercase{grüße}
\end{document}
~~~~

![image](https://github.com/user-attachments/assets/053d312f-48c4-4250-9c36-a29d9aa11f46)

But the same fails if the language is ngerman:

~~~~
\documentclass[]{article}
\usepackage[ngerman]{babel}
\babelprovide[casing=eszett]{ngerman} %german doesn't work either
\usepackage{fontspec}
\setmainfont{dejavusans}
\begin{document}
\MakeUppercase{grüße}
\end{document}
~~~~

![image](https://github.com/user-attachments/assets/92aa2573-5ab9-4958-95fc-102f093ad40a)

So how should it be done there? (It should naturally also work if more language like french are loaded with ldf-files.)

Side remark: I do find it highly confusing that "german" sometimes mean "new german" (in babelprovide) and sometimes "german-traditional" and would not mind if `german` generally means ngerman.

**Comment by jbezos** [comment] 2024-11-26 08:29
At a quick glance, I’ve found some code in `\extrasngerman` resetting the value of the tag to `de`. It doesn’t belong to the `babel` core (which sets correctly the tag to `de-x-eszett`), so I have to investigate, but I’d say there is some issue in `german.ldf`.

On the side remark. Agreed. Currently almost all languages names has been normalized to the Unicode CLDR.

**Comment by u-fischer** [comment] 2024-11-27 10:54
Ok looking at the documentation of babel-german I found that this works:

~~~~
\documentclass[]{article}
\usepackage[ngerman.capsz]{babel}
\usepackage{fontspec}
\setmainfont{dejavusans}
\begin{document}
\MakeUppercase{grüße}
\end{document}
~~~~

But I think that should be handled in a better way. Now we have `\babelprovide[casing=eszett]{german}` for german-traditional (hoping that this doesn't active ngerman hyphenation patterns) , `\usepackage[ngerman.capsz]{babel}` for ngerman, `\MakeUppercase[locale=de-x-eszett]{grüße}` for local adjustments and `\setmainlanguage[capitaleszett]{german}` with polyglossia. @jspitz, @josephwright, @FrankMittelbach  

> On the side remark. Agreed. Currently almost all languages names has been normalized to the Unicode CLDR.

Well I think this should be done here too. While trying out different variants I wasn't even able to tell which hyphenation patterns and german variant I actually got at the end.  german and ngerman should be synonyms everywhere and whoever wants traditional writing should use german-traditional.

**Comment by jbezos** [comment] 2024-11-29 10:48
I’m closing this issue because the problem is in the language style (reported to the maintainer).

**Closed by jbezos** 2024-11-29 10:48 UTC
Labels: report elsewhere
