### ISSUE TITLE
\unhbox of  arabic text cause an uncorrect result 

### ISSUE THREAD

**Issue by seloumi** [latex3/babel#25] opened 2019-08-21 19:02 UTC
Trying to use `bidipoem`  with `babel` package to write arabic poem I have a problem with the result 
``` latex
\documentclass{article}
\usepackage[nil,bidi=basic-r]{babel}
\usepackage{bidipoem}

\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

\renewcommand\poemcolsepskip{2cm}

{\baselineskip 24pt
\begin{traditionalpoem*}
أَنا الَّذي نَظَرَ الأَعمى إِلى أَدَبي & وَأَسمَعَت كَلِماتي مَن بِهِ صَمَمُ
أَنامُ مِلءَ جُفوني عَن شَوارِدِها & وَيَسهَرُ الخَلقُ جَرّاها وَيَختَصِمُ
وَجاهِلٍ مَدَّهُ في جَهلِهِ ضَحِكي & حَتّى أَتَتهُ يَدٌ فَرّاسَةٌ وَفَمُ
إِذا نَظَرتَ نُيوبَ اللَيثِ بارِزَةً & فَلا تَظُنَّنَّ أَنَّ اللَيثَ مُبتَسِمُ
\end{traditionalpoem*}
\par}

\end{document}
```
I searched the causes and I find that due to `\unhbox`  used by `bidipoem`.
 Here a simple example and the result 

```latex 
\documentclass{article}
\usepackage[nil,bidi=basic-r]{babel}
\babelprovide[import=ar-DZ, main]{arabic}
\babelfont{rm}{Amiri}

\begin{document}

\setbox0=\hbox{نص عربي}

\unhbox0

\end{document}
```

![image](https://user-images.githubusercontent.com/8249073/63460342-9fe00100-c456-11e9-9826-27f8d18cb712.png)

**log file** 
[test.log](https://github.com/latex3/babel/files/3526873/test.log)

**Comment by jbezos** [comment] 2019-08-23 14:25
The problem is Amiri uses the Private Use Area. Once the box is built, there is no information about the direction of the glyphs. If the direction is set explicitly with `\babelcharproperty` (I don't know the exact range), the text is rendered correctly:

    \documentclass{article}
    \usepackage[bidi=basic]{babel}
    \babelprovide[import=ar-DZ, main]{arabic}
    \babelfont{rm}{Amiri}
    
    % The following range is just a guess:
    \babelcharproperty{980000}[990000]{direction}{al}
    
    \begin{document}
    
    \setbox0=\hbox{نص عربي}
    
    \unhbox0
    
    \end{document}


You may use this macro as a workaround, but I must investigate a better solution.

**Comment by u-fischer** [comment] 2019-08-23 14:52
@jbezos  Marcel (@zauguin) is investigating bidi in luaotfload too. Perhaps some coordination is needed/useful, see e.g. https://github.com/latex3/luaotfload/pull/82.

**Comment by jbezos** [comment] 2019-08-23 17:11
Yes, I know (and these are great news), but I just got back from a trip. I still have to look at it.

**Comment by khaledhosny** [comment] 2019-10-01 10:16
> The problem is Amiri uses the Private Use Area.

What you are seeing is the way luaotfload handles glyph indices that don’t directly map to Unicode code points, Amiri itself does not use any PUA.

The real problem here is trying to apply BiDi on output glyphs, which by definition can not work since BiDi needs the original characters in their original order. Either unboxed nodes needs to carry the original direction information as well and BiDi algorithm need not be run again on them (needs changes to the engine I think, probably not easy to implement), or unboxing needs to be avoided altogether since it comes from a very simplistic view of modern text layout.

**Comment by khaledhosny** [comment] 2019-10-01 10:18
(also excuse my ignorance, but why unbox a box instead of using it as is?)

**Comment by davidcarlisle** [comment] 2019-10-01 10:25
@khaledhosny 

> (also excuse my ignorance, but why unbox a box instead of using it as is?)

latex (even with no packages loaded) does that quite a lot, eg list labels are set as

`      \hbox to\labelwidth {\unhbox\@tempboxa}%`

which shows the typical case, you box up text to find its natural width but then having decided by some calculation which width to use for all of them you unbox the texts allowing any glue within them to stretch or shrink to hit the target width.

The other use of course is to allow line breaking. (Although there are possibly less cases where you need to box first but still allow lines to break)

**Comment by khaledhosny** [comment] 2019-10-01 10:33
Well, then this needs to be dealt with as BiDi can’t be applied to the unboxed content in this case. BiDi would need to be applied at box creation time then the direction information somehow need to be carried over when unboxed.

This still might not give the expected output, since if the unboxed content became part of a larger chunk of text (e.g. part of a paragraph) the result of applying BiDi algorithm can be different than when processed standalone.

Like I said, boxing and unboxing seems to stem from a simplistic view of text layout (understandable given its age) and should be avoided. For example, the width of a piece of text does not necessarily equal the sum of the widths of its parts cut at different places. Multiple factors can changes the final glyphs (and thus the widths) depending on what context the text was in.

**Comment by davidcarlisle** [comment] 2019-10-01 10:44
@khaledhosny  yes I was not disagreeing with what you are saying but (as you note above) doing this right might require engine changes (or in luatex more lua code, I guess...) 

>  For example, the width of a piece of text does not necessarily equal the sum of the widths of its parts cut at different places.

yes that's true even with english of course but with the tools available in current tex engines if you want to implement a requirement like "set all the list labels to the width of the widest  label" then boxing and unboxing is the only tool available.

similarly `\makebox[2\width]{foo bar}`  to set some text to twice its natural width boxes it first (to work out `\width`) then unboxes it.

That said, it ought to be possible in the macro layer to (somehow) delimit text that has already been bidi processed and so mark directionality when unboxing. I think...

**Comment by khaledhosny** [comment] 2019-10-01 10:47
Babel could set an attribute indicating the resolved direction of the node (and hope it gets carried over correctly during text layout) and use it to reconstruct the direction of the unboxed content.

**Comment by jbezos** [comment] 2019-10-01 16:16
> What you are seeing is the way luaotfload handles glyph indices that don’t directly map to Unicode code points, Amiri itself does not use any PUA.

I see. Thank you. Anyway, `luaotfload` does, so problem it's still the PUA. I think this answers my question in #28 -- the font doesn't contain information about the bidi class of these glyphs.

The problem is the bidi algorithm is applied twice, when the box is built (the right place), and when it's unboxed. As the workaround with `\babelcharproperty` shows, with the proper bidi classes everything seems fine (babel assumes ‘L’ if unknown), so the solution, which I'm currently investigating, passes for either another default (eg, assume ‘AL’ is the script of the language is Arabic, a very crude guess) or deactivate somehow the bidi algorithm with glyphs in the PUA. I'm still not sure which solution actually works.

**Comment by jbezos** [comment] 2019-10-01 17:00
Or a flag with a lua property meaning ‘already processed with bidi’.

**Comment by khaledhosny** [comment] 2019-10-05 14:07
> > What you are seeing is the way luaotfload handles glyph indices that don’t directly map to Unicode code points, Amiri itself does not use any PUA.
> 
> I see. Thank you. Anyway, `luaotfload` does, so problem it's still the PUA. I think this answers my question in #28 -- the font doesn't contain information about the bidi class of these glyphs.

BiDi class is a character property not a glyph one i.e. glyphs don’t have a direction, the underlying characters do (it doesn’t help that the boundary between characters and glyphs is blurry in LuaTeX).

**Comment by jbezos** [comment] 2019-10-05 17:30
Yes, I know, but as far as Unicode is concerned, the initial, medial, final and isolated forms of a letter are the same character, and at this point of the internal process LuaTeX only sees the corresponding glyphs, which is was I was talking about. Anyway, this is just terminology.

**Comment by khaledhosny** [comment] 2019-10-05 17:32
Not sure I follow, but if the code is getting glyphs instead of characters then it is being run at the wrong stage of text processing i.e. the BiDi algorithm should be applied before any font layout.

**Comment by jbezos** [comment] 2019-10-05 17:38
And it's applied at the right place, before the font layout, so the box is correct. The problem is the bidi algorithm is applied again also when the box is unboxed, when characters has been already converted to glyphs in the internal processing.

**Comment by seloumi** [comment] 2019-10-08 11:57
Thanks @jbezos this solve the issue  👍

**Comment by Udi-Fogiel** [comment] 2024-06-09 21:14
I got bitten by this problem with `amsthm`, as the package box and unbox the theorem head.
```tex
\documentclass{article}
\usepackage{amsthm}
\newtheorem{thm}{משפט}

\usepackage[hebrew,bidi=basic,provide=*{babel}
\babelfont{rm}[Ligatures=TeX]{David CLM}

\begin{document}
\setcounter{thm}{11}
\begin{thm}[הלמה של צורן]
...
\end{thm}
\end{document}
``` 
I think at least mirroring should be done once...
What do you say about the following @jbezos ?
```diff
diff --git a/babel.dtx b/babel.dtx
index 6b6da6e..9a86a14 100644
--- a/babel.dtx
+++ b/babel.dtx
@@ -23182,6 +23182,11 @@ Babel.symbol_fonts[font.id('tencircw')] = true
 Babel.bidi_enabled = true
 Babel.mirroring_enabled = true
 
+luatexbase.new_attribute'babel_mirrored_attr'
+local mirrored_attr = luatexbase.attributes['babel_mirrored_attr']
+local has_attr = node.has_attribute
+local set_attr = node.set_attribute
+
 require('babel-data-bidi.lua')
 
 local characters = Babel.characters
@@ -23490,8 +23495,10 @@ function Babel.bidi(head, ispar, hdir)
       for r = first_on, q - 1 do
         nodes[r][2] = temp
         item = nodes[r][1]    -- MIRRORING
-        if Babel.mirroring_enabled and glyph_not_symbol_font(item)
-             and temp == 'r' and characters[item.char] then
+        if Babel.mirroring_enabled and glyph_not_symbol_font(item) 
+             and temp == 'r' and characters[item.char]
+             and not has_attr(item, mirrored_attr) then
+          set_attr(item, mirrored_attr, 1)
           local font_mode = ''
           if item.font > 0 and font.fonts[item.font].properties then
             font_mode = font.fonts[item.font].properties.mode
```
In general, couldn't that be done for all nodes? i.e. flagging them with some attribute, and if they already have don't process them?

**Comment by jbezos** [comment] 2024-06-10 15:52
> I think at least mirroring should be done once...
[...]
> In general, couldn't that be done for all nodes? i.e. flagging them with some attribute, and if they already have it don't process them?

Definitely: https://github.com/latex3/babel/issues/25#issuecomment-537130079.

I’ll take a look at your suggestion (although at this time I’m very busy).

**Comment by jbezos** [comment] 2024-06-10 15:59
Anyway, very likely you already know, but for reference with Harfbuzz the result it’s correct.

**Comment by Udi-Fogiel** [comment] 2024-06-19 02:45
> Definitely: [#25 (comment)](https://github.com/latex3/babel/issues/25#issuecomment-537130079).

😲

> I’ll take a look at your suggestion (although at this time I’m very busy).

Thanks! no pressure here. 

> Anyway, very likely you already know, but for reference with Harfbuzz the result it’s correct.

Yes, well `babel` does not mirror when HarfBuzz is used :)

**Comment by jbezos** [comment] 2024-06-24 16:26
@Udi-Fogiel I’ve more time again. I’ll resume the work on bidi writing. Ideally, we should address the whole issue, but perhaps as a first step we can focus on mirroring. I was trying to limit the use of attributes, but probably here it will be necessary one more.

**Comment by jbezos** [comment] 2024-08-15 08:12
I’m closing this issue because the last commit, and after extensive tests, seems to work. Only for `bidi=basic` (`bidi=basic-r` is still based on the PUA hack).

**Closed by jbezos** 2024-08-15 08:12 UTC
Labels: 🐞 bug, ⚙️ under study

**Comment by Udi-Fogiel** [comment] 2025-01-21 17:53
> I was trying to limit the use of attributes, but probably here it will be necessary one more.

Do babel already use some attributes? if so, does it need all values? if not, you can use one attribute for several properties setting the values as bitset.

**Comment by jbezos** [comment] 2025-01-24 17:12
Yes, `babel` uses a few attributes. I was revising the manual, so I hope they will be properly documented soon.
