### ISSUE TITLE
Greek as nonmain language AND Roman page numbers AND (makeindex OR xindex) = ☇

### ISSUE THREAD

**Issue by ghost** [latex3/babel#170] opened 2022-02-18 00:28 UTC
Feeding
```
\documentclass{book}
% \makeatletter
% \let\save@roman\@roman
% \let\save@Roman\@Roman
% \makeatother
\usepackage[greek,ngerman]{babel}
% \makeatletter
% \let\@roman\save@roman
% \let\@Roman\save@Roman
% \makeatother
\usepackage{makeidx}
\makeindex
\begin{document}
\pagenumbering{Roman}
\index{Text}Text
\printindex
\end{document}
```
as `mwe.tex` to `pdflatex` or `latex` leads to
```
\indexentry{Text}{{\fontencoding  {OT1}\selectfont  I}}
```
in the file `mwe.idx`. As a consequence, `makeindex mwe` or `xindex mwe` produce an empty file `mwe.ind`.  Moreover, if you  use `xindex mwe`, the program `xindex` fails with the output `...re/texlive/texmf-dist/tex/lualatex/xindex/xindex-lib.lua:524: bad argument #2 to 'format' (number expected, got nil)`. 
Used versions:
- pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2022/dev/Debian)
- LaTeX2e <2021-06-01> patch level 1
- L3 programming layer <2021-08-27>
- Document Class: book 2021/02/12 v1.4n
- bk10.clo 2021/02/12 v1.4n
- babel 2021/07/22 3.63
- babel.def 2021/07/22 3.63
- greek 2020/11/10 v1.10
- lgrenc.def 2020/10/13 2.0
- lgrenc.dfu 2019/07/11 1.7
- greek-fontenc.def 2020/10/30 2.0
- ngerman 2021/02/27 v2.13
- ngermanb 2021/02/27 v2.13
- makeidx 2014/09/29 v1.0m
- l3backend-dvips.def or l3backend-pdftex.def 2021-08-04
- lgrcmr.fd 2017/07/29 v1.2
- xindex 0.33 2021-08-15

Given http://tex.stackexchange.com/a/356649 and http://tex.stackexchange.com/a/633522 , a possible workaround would be to uncomment the commented lines or say 
```
\makeatletter
\def\@roman#1{\romannumeral #1}
\def\@Roman#1{\expandafter\@slowromancap\romannumeral#1@}
\makeatother
```
after calling `babel`. Another workaround is saying `\def\ensureascii#1{#1}` right after `\begin{document}` (cf. http://chat.stackexchange.com/transcript/message/60465101).
However, really, it would be probably much cleaner if greek-babel or babel don't redefine `\ensureascii` and/or `\@roman` and `\@Roman` for all languages. (If necessary, they may do it only within the scope of Greek-language commands or if Greek is the main document language).
The maintainer of `babel-greek` has been informed.

**Comment by hvoss49** [comment] 2022-02-19 19:12
use `lualatex` instead of `pdflatex` and it works. To me it looks like a problem with `babel`

**Comment by u-fischer** [comment] 2022-02-19 19:23
@hvoss49  it is  a problem steeming from babel-greek. It redefines \@roman and \@Roman (to ensure that they print roman numbers also when greek is active) and then they are no longer usable as page numbers in a index entry. Probably the best would be to change \index so that it can undo this definition locally.

**Comment by PeterMuellerr** [comment] 2022-02-19 19:27
> use `lualatex` instead of `pdflatex` and it works. To me it looks like a problem with `babel`
This is meant to be a bug report specifically against `pdflatex`/`latex` with `babel-greek`. (For `lualatex` and `xelatex` I do something else anyway in my larger, non-minimal documents.)

**Comment by jspitz** [comment] 2022-08-28 10:51
Similar problem with `backref` (see also plk/biblatex/issues/1175):
```tex
\documentclass[greek,english]{book}
\usepackage{babel}
\usepackage[backref=page]{hyperref}

%Workaround:
%\usepackage{etoolbox}
%\AtBeginDocument{\robustify\ensureascii}

\begin{document}
	\frontmatter
	\cite{article-minimal}
	\mainmatter
	\cite{article-minimal}
	\bibliographystyle{plain}
	\bibliography{xampl}
\end{document}
```

**Comment by jbezos** [comment] 2022-08-28 13:41
@jspitz There is a combination of factors, and as usual an `\edef`, with an unprotected expansion, is involved (in `hyperref`), which means `\protect`’s are just ignored, while `\robustify` relies on the primitive `\protected`. Although, IMO, the real culprit is the `\edef`, I’ll investigate if `\ensureascii` can be based on `\protected` instead of on `\protect`.

**Comment by u-fischer** [comment] 2022-08-28 14:56
@jbezos making \ensureascii robust will avoid the error but break the links. Hyperref will then try to create links to destinations like `page.\ensureascii {ii}`:

~~~~
pdfTeX warning (dest): name{page.\\ensureascii\040{ii}} has been referenced but
 does not exist, replaced by a fixed one

pdfTeX warning (dest): name{page.\\ensureascii\040{i}} has been referenced but 
does not exist, replaced by a fixed one
~~~~

I'm not sure how to get around the problem, but at the core hyperref assumes that `\thepage` is expandable and doesn't contain formatting instructions like `\fontencoding{OT1}\selectfont`.

**Comment by PeterMuellerr** [comment] 2022-08-28 15:27
First, you might wish to check whether, in the case of nonmain `greek`, babel(-greek) could redefine stuff it needs to redefine _only_ within the scope of language-changing commands and environments. (This holds for any language, not just for Greek. E.g., I have also `french` as a nonmain language and have been getting French-and-caption-related warnings in the log ever since though the only French text I have in a huge German document are a few French proper names. In the long run, useless warnings are nervous.) This will at least mitigate this issue and similar issues.
Second, if after that you still have a real-world error and need both ASCII and formatted page numbers, you might perhaps choose to split `\thepage` in two versions: one for printing (with any kinds of formatting commands that go with it), another for referencing (plain ASCII, without any kinds of commands including `\ensureascii`). Or, instead of trying to remove the formatting from the formatted page number (which is difficult) on need, you could _add_ formatting to a plain ASCII page number on need.

**Comment by jspitz** [comment] 2022-08-28 15:38
> First, you might wish to check whether, in the case of nonmain `greek`, babel(-greek) could redefine stuff it needs to redefine _only_ within the scope of language-changing commands and environments. 

Like this:

```diff
--- /usr/local/texlive/current/texmf-dist/tex/generic/babel-greek/greek.ldf
+++ /tmp/meld-tmp_0c8523p.ldf
@@ -104,6 +104,10 @@
     \makeatother
   }{}
 }
+\let\latin@roman\@roman
+\let\latin@Roman\@Roman
+\let\bbl@greek@roman\@roman
+\let\bbl@greek@Roman\@Roman
 \@ifl@aded{def}{lgrenc}{%
   \ProvideTextCommand{\textcopyright}{LGR}{\ensureascii{\textcopyright}}
   \ProvideTextCommand{\textregistered}{LGR}{\ensureascii{\textregistered}}
@@ -113,8 +117,8 @@
   \ProvideTextCommand{\textampersand}{LGR}{\ensureascii{\ltx@amp}}
   \DeclareRobustCommand{\&}{\ifmmode\ltx@amp\else\textampersand\fi}
   \ProvideTextCommand{\SS}{LGR}{\ensureascii{\SS}}
-  \def\@roman#1{\expandafter\ensureascii\expandafter{\romannumeral#1}}
-  \def\@Roman#1{\expandafter\ensureascii\expandafter{%
+  \def\bbl@greek@roman#1{\expandafter\ensureascii\expandafter{\romannumeral#1}}
+  \def\bbl@greek@Roman#1{\expandafter\ensureascii\expandafter{%
                 \expandafter\@slowromancap\romannumeral#1@}}
   \DeclareRobustCommand{\greektext}{%
     \fontencoding{LGR}\selectfont
@@ -486,6 +490,14 @@
   \DeclareTextCompositeCommand{\`}{LGR}{^^9f}{\LGR@hiatus}
   \addto\extraspolutonikogreek{\languageshorthands{greek}}%
   \declare@shorthand{greek}{~}{\greek@tilde}
+  \addto\extrasgreek{%
+    \let\@roman\bbl@greek@roman
+    \let\@Roman\bbl@greek@Roman
+  }
+  \addto\noextrasgreek{%
+    \let\@roman\latin@roman
+    \let\@Roman\latin@Roman
+  }
 }{} % End of LGR-specific code.
 \providecommand*{\anwtonos}{\textdexiakeraia}
 \providecommand*{\katwtonos}{\textaristerikeraia}
```

This won't help if Greek is the active language, so a fix at the core is still needed. But I think it should be done anyway.

**Comment by u-fischer** [comment] 2022-08-28 15:55
> babel(-greek) could redefine stuff it needs to redefine only within the scope of language-changing commands and environments.

Well that wouldn't help in the case of page numbers as the language scope in which such a page number is *stored* (with `\label` etc) can be different from the scope in which it is *used* (via `\ref` etc).

> you might perhaps choose to split \thepage in two versions:

That plan is better, one should store the number (e.g.) and the intended formatting (e.g. \roman). But the problem here is again with labels and ref: Even with hyperref, which extends the label system, there is not enough place to move both informations around.

**Comment by PeterMuellerr** [comment] 2022-08-28 16:10
> Well that wouldn't help in the case of page numbers as the language scope in which such a page number is _stored_ (with `\label` etc) can be different from the scope in which it is _used_ (via `\ref` etc).
Perhaps, one could think of attempting to store some of the necessary local data, such as the language or the formatting, together with or alongside the stored label and to use this data at the time of usage of the label.

**Comment by u-fischer** [comment] 2022-08-28 16:21
well you can try with zref, it allows you to store more data. But it will  not be trivial to format all locations like index and bibliographies where page numbers are used correctly. Imho the best is to drop LGR encoding and `\ensureascii` by using an unicode engine.

**Comment by PeterMuellerr** [comment] 2022-08-28 16:54
To the systems architect in me, storing more data seems to border on an small architectural change, which seems to require more work than a quick-and-dirty hack. (Architectural changes and cleanups for most software projects are inevitably required; if their code evolves in small quick-and-dirty steps, it usually becomes unmanageable ad-hoc spaghetti. I view switching to [Xe|Lua]LaTeX as another, more profound architectural change. Still, [pdf]latex is alive and does not have a trivial replacement everywhere yet: I personally dealt with svmono and arxiv.org.)

**Comment by jspitz** [comment] 2022-08-28 16:55
> > babel(-greek) could redefine stuff it needs to redefine only within the scope of language-changing commands and environments.
> 
> Well that wouldn't help in the case of page numbers as the language scope in which such a page number is _stored_ (with `\label` etc) can be different from the scope in which it is _used_ (via `\ref` etc).

True, but it helps in all cases where Greek is not active (but loaded), e.g. the MWE in https://github.com/latex3/babel/issues/170#issuecomment-1229431476. In any case, I don't see why babel-greek should globally redefine `\@roman` once and for all.

**Comment by u-fischer** [comment] 2022-08-28 17:12
> True, but it helps in all cases where Greek is not active (but loaded),

If you don't have references  to roman numbers in greek parts of your document, you can simply reinstate the default LaTeX definitions everywhere and be done with it. But if you have such references then they will error or give faulty links or faulty output with your solution.  So what do you gain?

**Comment by jspitz** [comment] 2022-08-28 17:16
@u-fischer you are right, I forgot about `\pageref` to non-Greek roman pages within Greek context. So I retract my proposal.

**Comment by jspitz** [comment] 2022-08-28 17:22
@PeterMuellerr FYI that's this case:
```tex
\documentclass[greek,english]{book}
\usepackage{babel}

\begin{document}
	\frontmatter
	a\label{x}
	\clearpage
	\selectlanguage{greek}Page \pageref{x}
\end{document}
```
This would falsely come out as `ι` (rather than `i`) if the `\@roman` redefinition would be restricted to Greek language context.

**Comment by PeterMuellerr** [comment] 2022-08-28 17:39
> ```
> \selectlanguage{greek}Page
> ```
Thanks! As of now, it comes out as “Παγε i”. I believe you concerning “ι” if you have tested this. I apologize for having forgotten that there is persistent, stored stuff that has to be dealt with, too. 
Anyway, is this a realistic example? Wouldn't you write, perhaps, `\selectlanguage{greek}Σελίδα \selectlanguage{english}\pageref{x}` instead of `\selectlanguage{greek}Page \pageref{x}`?

**Comment by jbezos** [comment] 2022-08-29 06:15
> making \ensureascii robust will avoid the error but break the links. Hyperref will then try to create links to destinations like `page.\ensureascii {ii}`:

@u-fischer You’ve closed my investigations before I started 🙂, but I was expecting something like that. Of course, the root of the problem is assuming `\thepage` is fully expandable. See, for example:

- https://tex.stackexchange.com/questions/627336/compilation-errors-when-babel-and-cleveref-are-included-and-other-errors-when/627447#627447 
- https://tex.stackexchange.com/questions/619875/greekbabel-cleveref-roman-pagenumbering-label/619885#comment1548033_619885

**But**, I agree `\roman` must *not* be redefined globally when Greek isn’t the main language, and the current maintainer of `babel-greek` has been informed. Maybe it's time to insist.

> Second, if after that you still have a real-world error and need both plain-text and formatted page numbers, you might perhaps choose to split \thepage in two versions: one for printing (with any kinds of formatting commands that go with it), another for referencing (plain text, without any kinds of commands including \ensureascii). 

@PeterMuellerr This would be the ideal solution, even if, as pointed out by Ulrike, it’s not trivial.

**Comment by u-fischer** [comment] 2022-08-29 07:41
> You’ve closed my investigations before I started

@jbezos well I think some investigation in this area are needed, not only for roman/greek. The backref example also fails for spanish, and a number of packages redefine also `\@arabic` which can lead to problems too. 

> Of course, the root of the problem is assuming \thepage is fully expandable

The root of the problem is that page numbers  are used in many places by various tools with differing requirements: makeindex  wants to sort them, biblatex wants to compress page references to ranges, hyperref wants to create destinations, links and page labels, the label/ref wants to move it through the aux, and the document wants to print them in various formattings depending on the current language and the place where it is printed. All this works fine if page numbers are expandable and expand to something simple but gets quite difficult if language depending formatting is added.

**Comment by jbezos** [comment] 2022-08-29 09:06
@u-fischer Or fancy, but valid, formats like 3▪4 (where 3 is the chapter and 4 the page in the chapter, and ▪ is your favorite bullet in your favorite font, or even an image).

**Comment by u-fischer** [comment] 2022-08-29 09:18
@jbezos Yes. If you want to investigate here an example. As you can see the main problem is the index and not so much hyperref. The example ignores the problem of multi languages. Also the `XXXX-` in definition of `\blub` is expandable, and so the not-protected version works in the index here (but break page links) but in in real world examples it would contain e.g. font selections command which can expand in the index and so would break there too. 

If someone could come up with a good idea how to handle the index I could add support in hyperref - but I won't add a variety of commands like `\ensureascii`  etc, it then should be one common command (or perhaps one for each numbering style) and the language files would have to coordinate their access to such a formatting command. 


~~~~
\documentclass[]{book}

\usepackage{index,etoolbox}
\makeindex
\usepackage[backref=page]{hyperref}

\makeatletter
\def\@roman#1{\expandafter\blub\expandafter{\romannumeral#1}}

% \newcommand\blub[1]{XXXX-#1} %not protected works more less in index, but breaks links
% \DeclareRobustCommand\blub[1]{XXXX-#1} robust 
\protected\def\blub#1{XXXX-#1} %protected %miss index entries

\pdfstringdefDisableCommands{\let\blub\@firstofone}
\patchcmd\hyper@link@{\edef\Hy@tempb{#3}}{\let\blub\@firstofone\edef\Hy@tempb{#3}}{}{\fail}

\begin{document}
\frontmatter 
	first page 
    \index{orange}
 \newpage 
    \cite{article-minimal}
    second page \phantomsection\label{abc}
\mainmatter
    mainmatter
    \index{duck}\index{orange}
    \pageref{abc}
	\cite{article-minimal}
	\bibliographystyle{plain}
	\bibliography{xampl}
    \printindex
\end{document}
~~~~

**Comment by PeterMuellerr** [comment] 2022-08-31 13:47
@u-fischer Concerning your proposal of using `zref`, do you think of something similar to the code below?

An investigation of concept; too simple for real life:
```
\documentclass{book}
\usepackage{zref}
\usepackage[greek,english]{babel}
\makeatletter
\zref@newlist{pageWithLang}
\zref@newprop*{lang}[english]{\languagename}
\zref@addprops{pageWithLang}{page,lang}
\newcommand{\labelWithLang}[1]{%
  \zref@setcurrent{page}{\thepage}%
  \zref@setcurrent{lang}{\languagename}%
  \zref@labelbylist{#1}{pageWithLang}%
}
\newcommand{\pagerefWithLang}[1]{%
  \foreignlanguage{%
    \zref@extract{#1}{lang}%
  }{%
    \zref@extract{#1}{page}%
  }%
}
\makeatother
\begin{document}
	\frontmatter
	\labelWithLang{englishPageLabel}English page\\
	Pages \pagerefWithLang{englishPageLabel} and \pagerefWithLang{greekPageLabel}.
	\clearpage
	\selectlanguage{greek}
	\labelWithLang{greekPageLabel}Ελληνική σελίδα\\
	Σελίδες \pagerefWithLang{englishPageLabel} και \pagerefWithLang{greekPageLabel}.
\end{document}
```
@jspitz Would such a code (perhaps, after some changes) jive with your proposal of local-only redefinitions of stuff in greek.ldf?

**Comment by jspitz** [comment] 2022-08-31 14:27
I am not sure I understand the plan. I don't think babel wants to load `zref`. Maybe in the long term, as LaTeX already started to include some of `zref`'s concepts (see `\@currentcounter`), the LaTeX kernel could provide a way to separate page numer formatting from the actual page number.

**Comment by PeterMuellerr** [comment] 2022-08-31 15:55
> I am not sure I understand the plan.

I thought that one of Ulrike's earlier suggestions was to use `zref`. The way I understood this, this would provide us with an opportunity to store the plain-text page number separately from language and formatting (given enough effort, no doubt about that). This would allow us to get rid of global redefinitions of stuff by `.ldf` similar to what you tried out. (As for what `babel` wants or doesn't want to do, it's probably not up to me to comment on that or to suggest that anyone does anything; as of now, I wouldn't be able to execute any changes in `babel` in general or `greek.ldf` in particular anyway.)

**Comment by jspitz** [comment] 2022-08-31 16:02
The approach helps to get a proper page reference also with the change to `greek.ldf` I proposed. But it's more a user workaround I think than a fix of the problem at the core.

**Comment by PeterMuellerr** [comment] 2022-08-31 16:36
> The approach helps to get a proper page reference also with the change to `greek.ldf` I proposed. But it's more a user workaround I think than a fix of the problem at the core.

Yes (because for the fix, it seems that we would have to change `\label`, `\ref`, and `\pageref` rather than to introduce `\labelWithLang`, `\pagerefWithLang`, … ).

**Comment by jbezos** [comment] 2022-12-08 08:28
Sure, the LGR is problematic, but the point here is `\roman` and `\Roman` are modified for *all* languages, while changes should be local or, at least, ‘global’ solely when Greek is the main language, so that `\thepage`, which is also ‘global’, prints the correct numeral. A second issue is `\makeindex` understands text and nothing else (related issue: https://github.com/latex3/babel/issues/26). On the other hand, I don’t think not supporting `greek` as a secondary language is not a real solution. 

I was working on a new feature (or, better, on improving an existing one), which will allow to write something like that:
```tex
\documentclass{article}
\usepackage[LGR, T1]{fontenc}
\usepackage[english]{babel}
\begin{document}
English \foreignlanguage{greek}{Ελληνικά} English.
\end{document}
```
(It’s based on https://latex3.github.io/babel/guides/locale-arabic.html#pdftex.)

**Comment by gmilde** [comment] 2022-12-11 23:28
Am  8.12.22 schrieb Javier Bezos:
> ... the point here is \roman and \Roman are
> modified for all languages, while changes should be local or, at least,
> ‘global’ solely when Greek is the main language

An example where the LGR-proof Roman numerals are required also with Greek
as secondary language:

~~~
\documentclass[a4,oneside]{book}

% Save original definition
\makeatletter
***@***.***@***@***.******@***.***
***@***.***@***@***.******@***.***
\makeatother

\usepackage[greek,english]{babel}

\makeatletter

% Restore original definition
***@***.******@***.***@***@***.***
***@***.******@***.***@***@***.***

% Make Roman numerals LGR-proof only if Greek is the active language:

% LGR-proof Roman numerals
***@***.***@roman#1{\expandafter\ensureascii\expandafter{\romannumeral#1}}
***@***.***@Roman#1{\expandafter\ensureascii\expandafter{%
                       ***@***.***\romannumeral#1@}}
\addto\extrasgreek{%
  ***@***.******@***.***@roman
  ***@***.******@***.***@Roman
}
\addto\noextrasgreek{%
  ***@***.******@***.***@***@***.***
  ***@***.******@***.***@***@***.***
}

\makeatother


\begin{document}
\frontmatter

\tableofcontents      % Check Roman page numbers!

\chapter{English Preface \label{ch:preface}}

Use case:
a document with Greek preface chapter and a table of contents.

\selectlanguage{greek}
\chapter{Greek Preface \label{ch:preface-greek}}

logos, kairos, irgendwas

\selectlanguage{english}
\mainmatter

\chapter{First Chapter \label{ch:1}}

The English preface'' is at page \pageref{ch:preface}.

The Greek preface'' is at page \pageref{ch:preface-greek}.

\selectlanguage{greek}

The English preface'' is at page \pageref{ch:preface}.

The Greek preface'' is at page \pageref{ch:preface-greek}.

\end{document}


> A second issue is \makeindex understands text and nothing else (related
> issue: #26).

It seems "makeindex" can handle TeX macros that have a replacement in
*.ist files, like

% save printable macros
merge_rule	"\\TeX"		"TeX"

Maybe we can fix "makeindex" ensuring `\ensureascii` ends up in the *.idx
file and add a merge_rule that removes it for the index generation?

Günter

**Comment by jbezos** [comment] 2022-12-12 15:54
👌 Good example. I’ll study it, but it seems this issue is going to become (another) ‘known issue‘ of the LGR encoding.

**Comment by gmilde** [comment] 2022-12-13 22:43
Maybe we need a new language option "global-lgr-fixes=[on|off]" or so.
After a transition period, the default could become "off".

**Comment by jbezos** [comment] 2022-12-26 16:50
I’m closing this issue for two reasons. (1) It’s an intrinsic limitation of the non-standard LGR encoding, which is not really part of the babel core. (2) There is now (3.84) a simple alternative to set more or less short Greek texts as a secondary language (see [What’s new in babel 3.84](https://latex3.github.io/babel/news/whats-new-in-babel-3.84.html#encodings-with-pdftex-and-babelprovide)).

**Closed by jbezos** 2022-12-26 16:50 UTC

**Comment by gmilde** [comment] 2023-01-13 11:50
Thank you for providing another workaround (for small Greek text parts) in Babel 3.84.
 (There is a small but confusing documentation error in [What’s new in babel 3.84](https://latex3.github.io/babel/news/whats-new-in-babel-3.84.html#encodings-with-pdftex-and-babelprovide)):
`fontspec` -> `fontenc` (you cannot set a font encoding with `fontspec`).)

This adds one level of language support (hyphenation), but would not help in documents requiring
translated auto-strings (e.g. for a Greek abstract). I'd like to see more testing and better documentation.

I prepared a new version for contributed [babel-greek](https://codeberg.org/milde/greek-tex/src/branch/master/babel-greek) package and opened an issue there https://codeberg.org/milde/greek-tex/issues/1.

**Comment by gmilde** [comment] 2023-01-13 12:03
@u-fischer @jspitz
> ... I could add support in hyperref - but I won't add a variety of commands like `\ensureascii` etc, it then should be one common command (or perhaps one for each numbering style) and the language files would have to coordinate their access to such a formatting command.

babel-greek tries to solve this with a new "TextCommand" (see [commit 0f56b](https://codeberg.org/milde/greek-tex/commit/0f56b723c2f360f0a5c0e14c94b02ba80b9ac10b)).
~~~
  \ProvideTextCommandDefault{\EnsureStandardFontEncoding}{\@firstofone}
  \ProvideTextCommand{\EnsureStandardFontEncoding}{LGR}[1]{%
                                                      \ensureascii{#1}}
  \AtBeginDocument{\@ifpackageloaded{hyperref}
                     {\pdfstringdefDisableCommands{%
                         \let\EnsureStandardFontEncoding\@firstofone}}
                     {}}
~~~
This seems to fix the "backref" issues in my tests.
Is there anything missing regarding hyperref?
