### ISSUE TITLE
babel plus multicolumn plus font Amiri seems to break Arabic document

### ISSUE THREAD

**Issue by hpvd** [latex3/babel#233] opened 2023-04-08 13:01 UTC
babel plus 3 column plus font Amiri seems to break arabic document
first seen in combination with linebreaker, see
https://github.com/michal-h21/linebreaker/issues/9

```
\listfiles
\documentclass[A4]{book}

\usepackage{multicol}
\usepackage{lipsum}
\usepackage{linebreaker}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{times}
\babelfont[arabic]{rm}{Amiri}


\begin{document}

\begin{multicols}{3}
    \lipsum[1-6]

    \begin{otherlanguage}{arabic}
        لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
        نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
        يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
        السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
        الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
        ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.\par
    \end{otherlanguage}
\end{multicols}

\end{document}

```

![2023-04-08_14h06_02](https://user-images.githubusercontent.com/5681880/230722554-f8d11b0c-a60c-41ab-a618-27a51e5b6a18.png)

**Comment by jbezos** [comment] 2023-04-08 15:29
Works for me with an updated TeXLive, w/ and w/o `linebreaker` (sadly, `linebreaker` doesn‘t identify itself).

**Comment by hpvd** [comment] 2023-04-08 15:38
hmmm interesting. Thanks for this fast testing.

Im using latest miktex (packages versions updates from today)
```
*File List*
    book.cls    2022/07/02 v1.4n Standard LaTeX document class
    bk10.clo    2022/07/02 v1.4n Standard LaTeX file (size option)
multicol.sty    2021/11/30 v1.9d multicolumn formatting (FMi)
  lipsum.sty    2021-09-20 v2.7 150 paragraphs of Lorem Ipsum dummy text
l3keys2e.sty    2023-01-16 LaTeX2e option processing using LaTeX3 keys
   expl3.sty    2023-03-30 L3 programming layer (loader) 
l3backend-luatex.def    2023-03-30 L3 backend support: PDF output (LuaTeX)
  lipsum.ltd
linebreaker.sty    
luatexbase.sty    2015/10/04 v1.3 luatexbase interface to LuaTeX 
ctablestack.sty    2015/10/01 v1.0 Catcode table stable support
   babel.sty    2023/03/28 3.87 The Babel package
 bblopts.cfg    2005/09/08 v0.1 add Arabic and Farsi to "declared" options of b
abel
     nil.ldf    2023/03/28 3.87 Nil language
babel-english.tex
babel-arabic.tex
babel-ca-islamic.tex
fontspec.sty    2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2023-01-16 L3 Experimental document command parser
fontspec-luatex.sty    2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX

 fontenc.sty    2021/04/29 v2.0v Standard LaTeX package
fontspec.cfg
  ts1cmr.fd    2022/07/10 v2.5l Standard LaTeX font definitions
 ***********
```

**Comment by hpvd** [comment] 2023-04-08 15:41
What do you mean with
> (sadly, `linebreaker` doesn‘t identify itself).
?

there are some thoughts on visual highlighting some things...
https://github.com/michal-h21/linebreaker/issues/5

**Comment by hpvd** [comment] 2023-04-08 16:17
Updating Amiri to latest release directly from
https://github.com/aliftype/amiri/releases
instead of downloaded from https://fonts.google.com/specimen/Amiri
doesn't help on my site

**Comment by u-fischer** [comment] 2023-04-08 18:21
it works for me in miktex. The amiri font used is the one which comes with miktex: `/MiKTeX/fonts/truetype/public/amiri/amiri-regular.ttf`

**Comment by hpvd** [comment] 2023-04-08 18:52
many thanks for testing!

Investigated a little further:
-after the first run (in fresh folder) everything looks fine on my side too
- after the second run, it's broken

see:
![2023-04-08_20h48_04](https://user-images.githubusercontent.com/5681880/230738132-2f1f8900-af4b-4454-889f-184be589319d.png)

**Comment by hpvd** [comment] 2023-04-08 18:55
(uploaded screenshot changed)

-> could you reproduce this?

(Im using the same font as described by @u-fischer)

**Comment by u-fischer** [comment] 2023-04-08 18:58
No I can't reproduce it. Also you are not compiling the example you posted. Your screenshot shows a sans serif font.

**Comment by hpvd** [comment] 2023-04-08 19:00
sorry 

changed
-  font for test and 
- fixed option to \documentclass[a4paper]

direct new copy:

```
\listfiles
\documentclass[a4paper]{book}

\usepackage{multicol}
\usepackage{lipsum}
\usepackage{linebreaker}
\usepackage[bidi = basic]{babel}

\babelprovide[main, import]{english}
\babelprovide[import]{arabic}

\babelfont[english]{rm}{arial}
\babelfont[arabic]{rm}{Amiri}


\begin{document}

\begin{multicols}{3}
    \lipsum[1-6]

    \begin{otherlanguage}{arabic}
        لكن لا بد أن أوضح لك أن كل هذه الأفكار المغلوطة حول استنكار  النشوة وتمجيد الألم
        نشأت بالفعل، وسأعرض لك التفاصيل لتكتشف حقيقة وأساس تلك السعادة البشرية، فلا أحد
        يرفض أو يكره أو يتجنب الشعور بالسعادة، ولكن بفضل هؤلاء الأشخاص الذين لا يدركون بأن
        السعادة لا بد أن نستشعرها بصورة أكثر عقلانية ومنطقية فيعرضهم هذا لمواجهة الظروف
        الأليمة، وأكرر بأنه لا يوجد من يرغب في الحب ونيل المنال ويتلذذ بالآلام، الألم هو الألم
        ولكن نتيجة لظروف ما قد تكمن السعاده فيما نتحمله من كد وأسي.\par
    \end{otherlanguage}
\end{multicols}

\end{document}
```

**Comment by hpvd** [comment] 2023-04-08 19:02
double checked: can easily reproduce

**Comment by u-fischer** [comment] 2023-04-08 19:09
works fine. Show your log-file.

**Comment by hpvd** [comment] 2023-04-08 19:15
This is LuaHBTeX, Version 1.16.0 (MiKTeX 23.1) (format=lualatex 2023.4.8)  8 APR 2023 21:12
 restricted system commands enabled.
**Test-Arba.tex
(./Test-Arba.tex
LaTeX2e <2022-11-01> patch level 1
Lua module: luaotfload 2022-10-03 3.23 Lua based OpenType font support
Lua module: lualibs 2022-10-04 2.75 ConTeXt Lua standard libraries.
Lua module: lualibs-extended 2022-10-04 2.75 ConTeXt Lua libraries -- extended c
ollection.
luaotfload | conf : Root cache directory is "C:/Users/ME/AppData/Local/MiKT
eX/luatex-cache/generic/names".
luaotfload | init : Loading fontloader "fontloader-2022-10-03.lua" from kpse-res
olved path "C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/luatex/luaotfload
/fontloader-2022-10-03.lua".
Lua-only attribute luaotfload@noligature = 1
luaotfload | init : Context OpenType loader version 3.120
Inserting `luaotfload.node_processor' in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' in `hpack_filter'.
Inserting `luaotfload.glyph_stream' in `glyph_stream_provider'.
Inserting `luaotfload.define_font' in `define_font'.
Lua-only attribute luaotfload_color_attribute = 2
luaotfload | conf : Root cache directory is "C:/Users//AppData/Local/MiKT
eX/luatex-cache/generic/names".
Inserting `luaotfload.harf.strip_prefix' in `find_opentype_file'.
Inserting `luaotfload.harf.strip_prefix' in `find_truetype_file'.
Removing  `luaotfload.glyph_stream' from `glyph_stream_provider'.
Inserting `luaotfload.harf.glyphstream' in `glyph_stream_provider'.
Inserting `luaotfload.harf.finalize_vlist' in `post_linebreak_filter'.
Inserting `luaotfload.harf.finalize_hlist' in `hpack_filter'.
Inserting `luaotfload.cleanup_files' in `wrapup_run'.
Inserting `luaotfload.harf.finalize_unicode' in `finish_pdffile'.
Inserting `luaotfload.glyphinfo' in `glyph_info'.
Lua-only attribute luaotfload.letterspace_done = 3
Inserting `luaotfload.aux.set_sscale_dimens' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_font_index' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.patch_cambria_domh' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.fixup_fontdata' in `luaotfload.patch_font_unsafe'.
Inserting `luaotfload.aux.set_capheight' in `luaotfload.patch_font'.
Inserting `luaotfload.aux.set_xheight' in `luaotfload.patch_font'.
Inserting `luaotfload.rewrite_fontname' in `luaotfload.patch_font'. L3 programm
ing layer <2023-03-30>
Inserting `tracingstacklevels' in `input_level_string'.
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/base/book.cls
Document Class: book 2022/07/02 v1.4n Standard LaTeX document class
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/base/bk10.clo
File: bk10.clo 2022/07/02 v1.4n Standard LaTeX file (size option)
luaotfload | db : Font names database loaded from C:/Users/ME/AppData/Local
/MiKTeX/luatex-cache/generic/names/luaotfload-names.luc.gz)
\c@part=\count183
\c@chapter=\count184
\c@section=\count185
\c@subsection=\count186
\c@subsubsection=\count187
\c@paragraph=\count188
\c@subparagraph=\count189
\c@figure=\count190
\c@table=\count191
\abovecaptionskip=\skip48
\belowcaptionskip=\skip49
\bibindent=\dimen139
)
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/tools/multicol.sty
Package: multicol 2021/11/30 v1.9d multicolumn formatting (FMi)
\c@tracingmulticols=\count192
\mult@box=\box51
\multicol@leftmargin=\dimen140
\c@unbalance=\count193
\c@collectmore=\count194
\doublecol@number=\count195
\multicoltolerance=\count196
\multicolpretolerance=\count197
\full@width=\dimen141
\page@free=\dimen142
\premulticols=\dimen143
\postmulticols=\dimen144
\multicolsep=\skip50
\multicolbaselineskip=\skip51
\partial@page=\box52
\last@line=\box53
\maxbalancingoverflow=\dimen145
\mult@rightbox=\box54
\mult@grightbox=\box55
\mult@firstbox=\box56
\mult@gfirstbox=\box57
\@tempa=\box58
\@tempa=\box59
\@tempa=\box60
\@tempa=\box61
\@tempa=\box62
\@tempa=\box63
\@tempa=\box64
\@tempa=\box65
\@tempa=\box66
\@tempa=\box67
\@tempa=\box68
\@tempa=\box69
\@tempa=\box70
\@tempa=\box71
\@tempa=\box72
\@tempa=\box73
\@tempa=\box74
\@tempa=\box75
\@tempa=\box76
\@tempa=\box77
\@tempa=\box78
\@tempa=\box79
\@tempa=\box80
\@tempa=\box81
\@tempa=\box82
\@tempa=\box83
\@tempa=\box84
\@tempa=\box85
\@tempa=\box86
\@tempa=\box87
\@tempa=\box88
\@tempa=\box89
\@tempa=\box90
\@tempa=\box91
\@tempa=\box92
\@tempa=\box93
\c@minrows=\count198
\c@columnbadness=\count199
\c@finalcolumnbadness=\count266
\last@try=\dimen146
\multicolovershoot=\dimen147
\multicolundershoot=\dimen148
\mult@nat@firstbox=\box94
\colbreak@box=\box95
\mc@col@check@num=\count267
)
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/lipsum/lipsum.sty
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/l3packages/l3keys2e/l
3keys2e.sty
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/l3kernel/expl3.sty
Package: expl3 2023-03-30 L3 programming layer (loader) 

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/l3backend/l3backend-l
uatex.def
File: l3backend-luatex.def 2023-03-30 L3 backend support: PDF output (LuaTeX)
\l__color_backend_stack_int=\count268
Inserting `l3color' in `luaotfload.parse_color'.
\l__pdf_internal_box=\box96
))
Package: l3keys2e 2023-01-16 LaTeX2e option processing using LaTeX3 keys
)
Package: lipsum 2021-09-20 v2.7 150 paragraphs of Lorem Ipsum dummy text
\g__lipsum_par_int=\count269
\l__lipsum_a_int=\count270
\l__lipsum_b_int=\count271

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/lipsum/lipsum.ltd.tex
))
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/lualatex/linebreaker/linebr
eaker.sty
Package: linebreaker 

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/luatex/luatexbase/luatexbas
e.sty
Package: luatexbase 2015/10/04 v1.3 luatexbase interface to LuaTeX 

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/luatex/ctablestack/ctablest
ack.sty
Package: ctablestack 2015/10/01 v1.0 Catcode table stable support
\@catcodetablestackcnt=\count272
)
\CatcodeTableOther=\catcodetable12
\CatcodeTableExpl=\catcodetable13
)
Inserting `new linebreak callback' in `linebreak_filter'.
Inserting `new linebreak callback' in `post_linebreak_filter'.
Inserting `Our overfull box reporting function' in `hpack_quality'.)
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/babel.sty
Package: babel 2023/03/28 3.87 The Babel package

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/luababel.def
\bbl@readstream=\read2
\l@afrikaans=\language2
Package babel Info: Non-standard hyphenation setup on input line 118.
\l@ancientgreek=\language3
\l@armenian=\language4
\l@assamese=\language5
\l@basque=\language6
\l@belarusian=\language7
\l@bengali=\language8
\l@bokmal=\language9
\l@bulgarian=\language10
\l@catalan=\language11
\l@churchslavonic=\language12
\l@classiclatin=\language13
\l@coptic=\language14
\l@croatian=\language15
\l@czech=\language16
\l@danish=\language17
\l@dutch=\language18
\l@esperanto=\language19
\l@estonian=\language20
\l@ethiopic=\language21
\l@finnish=\language22
\l@french=\language23
\l@friulan=\language24
\l@galician=\language25
\l@georgian=\language26
\l@german=\language27
\l@greek=\language28
\l@gujarati=\language29
\l@hindi=\language30
\l@hungarian=\language31
\l@icelandic=\language32
\l@indonesian=\language33
\l@interlingua=\language34
\l@irish=\language35
\l@italian=\language36
\l@kannada=\language37
\l@kurmanji=\language38
\l@latin=\language39
\l@latvian=\language40
\l@lithuanian=\language41
\l@liturgicallatin=\language42
\l@macedonian=\language43
\l@malayalam=\language44
\l@marathi=\language45
\l@mongolian=\language46
\l@mongolianlmc=\language47
\l@monogreek=\language48
\l@ngerman=\language49
\l@nynorsk=\language50
\l@occitan=\language51
\l@oriya=\language52
\l@pali=\language53
\l@panjabi=\language54
\l@piedmontese=\language55
\l@polish=\language56
\l@portuguese=\language57
\l@romanian=\language58
\l@romansh=\language59
\l@russian=\language60
\l@sanskrit=\language61
\l@serbian=\language62
\l@serbianc=\language63
\l@slovak=\language64
\l@slovenian=\language65
\l@spanish=\language66
\l@swedish=\language67
\l@swissgerman=\language68
\l@tamil=\language69
\l@telugu=\language70
\l@thai=\language71
\l@turkish=\language72
\l@turkmen=\language73
\l@ukenglish=\language74
\l@ukrainian=\language75
\l@uppersorbian=\language76
\l@usenglishmax=\language77
\l@welsh=\language78
\babelcatcodetablenum=\catcodetable14
\bbl@pattcodes=\catcodetable15
)
\babel@savecnt=\count273
\U@D=\dimen149
\l@unhyphenated=\language79
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/luababel.def
\bbl@attr@locale=\attribute4
Removing  `luaotfload.node_processor' from `pre_linebreak_filter'.
Inserting `Babel.pre_otfload_v' in `pre_linebreak_filter'.
Inserting `luaotfload.node_processor' in `pre_linebreak_filter'.
Removing  `luaotfload.node_processor' from `hpack_filter'.
Removing  `luaotfload.harf.finalize_hlist' from `hpack_filter'.
Inserting `Babel.pre_otfload_h' in `hpack_filter'.
Inserting `luaotfload.node_processor' in `hpack_filter'.
Inserting `luaotfload.harf.finalize_hlist' in `hpack_filter'.
\bbl@attr@dir=\attribute5
)
*************************************
* Local config file bblopts.cfg used
*
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/arabi/bblopts.cfg
File: bblopts.cfg 2005/09/08 v0.1 add Arabic and Farsi to "declared" options of
 babel
)
Package babel Info: You haven't specified a language as a class or package
(babel)             option. I'll load 'nil'. Reported on input line 4429.

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/nil.ldf
Language: nil 2023/03/28 3.87 Nil language
\l@nil=\language80
))
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/locale/en/bab
el-english.tex)
Package babel Info: Importing data for english
(babel)             from babel-en.ini. Reported on input line 9.

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/locale/ar/bab
el-arabic.tex)
Package babel Info: Importing data for arabic
(babel)             from babel-ar.ini. Reported on input line 10.
Package babel Info: Hyphen rules for 'arabic' set to \l@english
(babel)             (\language0). Reported on input line 10.

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/babel/babel-ca-isla
mic.tex)
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/fontspec/fontspec.sty

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/l3packages/xparse/xpa
rse.sty
Package: xparse 2023-01-16 L3 Experimental document command parser
)
Package: fontspec 2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX
Lua module: fontspec 2022/01/15 2.8a Font selection for XeLaTeX and LuaLaTeX
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/fontspec/fontspec-lua
tex.sty
Package: fontspec-luatex 2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaT
eX
\l__fontspec_script_int=\count274
\l__fontspec_language_int=\count275
\l__fontspec_strnum_int=\count276
\l__fontspec_tmp_int=\count277
\l__fontspec_tmpa_int=\count278
\l__fontspec_tmpb_int=\count279
\l__fontspec_tmpc_int=\count280
\l__fontspec_em_int=\count281
\l__fontspec_emdef_int=\count282
\l__fontspec_strong_int=\count283
\l__fontspec_strongdef_int=\count284
\l__fontspec_tmpa_dim=\dimen150
\l__fontspec_tmpb_dim=\dimen151
\l__fontspec_tmpc_dim=\dimen152

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/base/fontenc.sty
Package: fontenc 2021/04/29 v2.0v Standard LaTeX package
)
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/fontspec/fontspec.cfg
))) (./Test-Arba.aux

Package babel Info: The following font families will use the default
(babel)             settings for all or some languages:
(babel)             * \rmfamily = lmr
(babel)               [lmroman10-regular]:+tlig;
(babel)             * \sffamily = lmss
(babel)               [lmsans10-regular]:+tlig;
(babel)             * \ttfamily = lmtt
(babel)               [lmmono10-regular]:
(babel)             There is nothing intrinsically wrong with it, but
(babel)             'babel' will no set Script and Language, which could
(babel)             be relevant in some languages. If your document uses
(babel)             these families, consider redefining them with \babelfont.
(babel)             Reported on input line 3.

luaotfload | cache : Lookup cache loaded from C:/Users/ME/AppData/Local/MiK
TeX/luatex-cache/generic/names/luaotfload-lookup-cache.luc.
luaotfload | aux : font no 20 (nil) defines no feature for script latn with lang
uage eng
luaotfload | aux : font no 27 (nil) does not define feature smcp for script latn
 with language dflt
luaotfload | aux : font no 28 (nil) does not define feature smcp for script latn
 with language dflt

Package fontspec Info: Font family 'arial(0)' created for font 'arial' with
(fontspec)             options [Ligatures=TeX,Script=Latin,Language=English].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"arial:mode=node;script=latn;language=dflt;+tlig;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.:
(fontspec)             <->"arial:mode=node;script=latn;language=dflt;+tlig;+smc
p;"
(fontspec)             - 'bold' (b/n) with NFSS spec.:
(fontspec)             <->"arial/B:mode=node;script=latn;language=dflt;+tlig;"
(fontspec)             - 'bold small caps'  (b/sc) with NFSS spec.:
(fontspec)             <->"arial/B:mode=node;script=latn;language=dflt;+tlig;+s
mcp;"
(fontspec)             - 'italic' (m/it) with NFSS spec.:
(fontspec)             <->"arial/I:mode=node;script=latn;language=dflt;+tlig;"
(fontspec)             - 'italic small caps'  (m/scit) with NFSS spec.: 
(fontspec)             - 'bold italic' (b/it) with NFSS spec.:
(fontspec)             <->"arial/BI:mode=node;script=latn;language=dflt;+tlig;"

(fontspec)             - 'bold italic small caps'  (b/scit) with NFSS spec.: 

luaotfload | aux : font no 36 (nil) does not define feature smcp for script arab
 with language ara
luaotfload | aux : font no 37 (nil) does not define feature smcp for script arab
 with language ara
luaotfload | aux : font no 38 (nil) does not define feature smcp for script arab
 with language ara
luaotfload | aux : font no 39 (nil) does not define feature smcp for script arab
 with language ara

Package fontspec Info: Font family 'Amiri(0)' created for font 'Amiri' with
(fontspec)             options [Ligatures=TeX,Script=Arabic,Language=Arabic].
(fontspec)              
(fontspec)              This font family consists of the following NFSS
(fontspec)             series/shapes:
(fontspec)              
(fontspec)             - 'normal' (m/n) with NFSS spec.:
(fontspec)             <->"Amiri:mode=node;script=arab;language=ARA;+tlig;"
(fontspec)             - 'small caps'  (m/sc) with NFSS spec.: 
(fontspec)             - 'bold' (b/n) with NFSS spec.:
(fontspec)             <->"Amiri/B:mode=node;script=arab;language=ARA;+tlig;"
(fontspec)             - 'bold small caps'  (b/sc) with NFSS spec.: 
(fontspec)             - 'italic' (m/it) with NFSS spec.:
(fontspec)             <->"Amiri/I:mode=node;script=arab;language=ARA;+tlig;"
(fontspec)             - 'italic small caps'  (m/scit) with NFSS spec.: 
(fontspec)             - 'bold italic' (b/it) with NFSS spec.:
(fontspec)             <->"Amiri/BI:mode=node;script=arab;language=ARA;+tlig;"
(fontspec)             - 'bold italic small caps'  (b/scit) with NFSS spec.: 

)
\openout1 = Test-Arba.aux

LaTeX Font Info:    Checking defaults for OML/cmm/m/it on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for OMS/cmsy/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for OT1/cmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for T1/cmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for TS1/cmr/m/n on input line 16.
LaTeX Font Info:    Trying to load font information for TS1+cmr on input line 1
6.
 (C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/latex/base/ts1cmr.fd
File: ts1cmr.fd 2022/07/10 v2.5l Standard LaTeX font definitions
)
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for TU/lmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for OMX/cmex/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
LaTeX Font Info:    Checking defaults for U/cmr/m/n on input line 16.
LaTeX Font Info:    ... okay on input line 16.
Removing  `Babel.pre_otfload_h' from `hpack_filter'.
Removing  `luaotfload.node_processor' from `hpack_filter'.
Removing  `luaotfload.harf.finalize_hlist' from `hpack_filter'.
Inserting `Babel.math_box_dir' in `hpack_filter'.
Inserting `Babel.pre_otfload_h' in `hpack_filter'.
Inserting `luaotfload.node_processor' in `hpack_filter'.
Inserting `luaotfload.harf.finalize_hlist' in `hpack_filter'.

Package fontspec Info: Adjusting the maths setup (use [no-math] to avoid
(fontspec)             this).

\symlegacymaths=\mathgroup4
LaTeX Font Info:    Overwriting symbol font `legacymaths' in version `bold'
(Font)                  OT1/cmr/m/n --> OT1/cmr/bx/n on input line 16.
LaTeX Font Info:    Redeclaring math accent \acute on input line 16.
LaTeX Font Info:    Redeclaring math accent \grave on input line 16.
LaTeX Font Info:    Redeclaring math accent \ddot on input line 16.
LaTeX Font Info:    Redeclaring math accent \tilde on input line 16.
LaTeX Font Info:    Redeclaring math accent \bar on input line 16.
LaTeX Font Info:    Redeclaring math accent \breve on input line 16.
LaTeX Font Info:    Redeclaring math accent \check on input line 16.
LaTeX Font Info:    Redeclaring math accent \hat on input line 16.
LaTeX Font Info:    Redeclaring math accent \dot on input line 16.
LaTeX Font Info:    Redeclaring math accent \mathring on input line 16.
LaTeX Font Info:    Redeclaring math symbol \colon on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Gamma on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Delta on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Theta on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Lambda on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Xi on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Pi on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Sigma on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Upsilon on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Phi on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Psi on input line 16.
LaTeX Font Info:    Redeclaring math symbol \Omega on input line 16.
LaTeX Font Info:    Redeclaring math symbol \mathdollar on input line 16.
LaTeX Font Info:    Redeclaring symbol font `operators' on input line 16.
LaTeX Font Info:    Encoding `OT1' has changed to `TU' for symbol font
(Font)              `operators' in the math version `normal' on input line 16.
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  OT1/cmr/m/n --> TU/arial(0)/m/n on input line 16.
LaTeX Font Info:    Encoding `OT1' has changed to `TU' for symbol font
(Font)              `operators' in the math version `bold' on input line 16.
LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
(Font)                  OT1/cmr/bx/n --> TU/arial(0)/m/n on input line 16.
LaTeX Font Info:    Overwriting symbol font `operators' in version `normal'
(Font)                  TU/arial(0)/m/n --> TU/arial(0)/m/n on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `normal'
(Font)                  OT1/cmr/m/it --> TU/arial(0)/m/it on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathbf' in version `normal'
(Font)                  OT1/cmr/bx/n --> TU/arial(0)/b/n on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `normal'
(Font)                  OT1/cmss/m/n --> TU/lmss/m/n on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `normal'
(Font)                  OT1/cmtt/m/n --> TU/lmtt/m/n on input line 16.
LaTeX Font Info:    Overwriting symbol font `operators' in version `bold'
(Font)                  TU/arial(0)/m/n --> TU/arial(0)/b/n on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathit' in version `bold'
(Font)                  OT1/cmr/bx/it --> TU/arial(0)/b/it on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathsf' in version `bold'
(Font)                  OT1/cmss/bx/n --> TU/lmss/b/n on input line 16.
LaTeX Font Info:    Overwriting math alphabet `\mathtt' in version `bold'
(Font)                  OT1/cmtt/m/n --> TU/lmtt/b/n on input line 16.

(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/hyph-utf8/loadhyph/
loadhyph-la.tex UTF-8 Latin hyphenation patterns
(C:/Users/ME/AppData/Local/Programs/MiKTeX/tex/generic/hyph-utf8/patterns/
tex/hyph-la.tex))
LaTeX Font Info:    Font shape `TU/arial(0)/m/sl' in size <10> not available
(Font)              Font shape `TU/arial(0)/m/it' tried instead on input line 2
0.
 [1{C:/Users/ME/AppData/Local/MiKTeX/fonts/map/pdftex/pdftex.map}

] [2] (./Test-Arba.aux)

 *File List*
    book.cls    2022/07/02 v1.4n Standard LaTeX document class
    bk10.clo    2022/07/02 v1.4n Standard LaTeX file (size option)
multicol.sty    2021/11/30 v1.9d multicolumn formatting (FMi)
  lipsum.sty    2021-09-20 v2.7 150 paragraphs of Lorem Ipsum dummy text
l3keys2e.sty    2023-01-16 LaTeX2e option processing using LaTeX3 keys
   expl3.sty    2023-03-30 L3 programming layer (loader) 
l3backend-luatex.def    2023-03-30 L3 backend support: PDF output (LuaTeX)
  lipsum.ltd
linebreaker.sty    
luatexbase.sty    2015/10/04 v1.3 luatexbase interface to LuaTeX 
ctablestack.sty    2015/10/01 v1.0 Catcode table stable support
   babel.sty    2023/03/28 3.87 The Babel package
 bblopts.cfg    2005/09/08 v0.1 add Arabic and Farsi to "declared" options of b
abel
     nil.ldf    2023/03/28 3.87 Nil language
babel-english.tex
babel-arabic.tex
babel-ca-islamic.tex
fontspec.sty    2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX
  xparse.sty    2023-01-16 L3 Experimental document command parser
fontspec-luatex.sty    2022/01/15 v2.8a Font selection for XeLaTeX and LuaLaTeX

 fontenc.sty    2021/04/29 v2.0v Standard LaTeX package
fontspec.cfg
  ts1cmr.fd    2022/07/10 v2.5l Standard LaTeX font definitions
 ***********

)

Here is how much of LuaTeX's memory you used:
 5155 strings out of 478280
 745247,1977958 words of node,token memory allocated
 656166 words of node memory still in use:
   2849 hlist, 1 vlist, 1 rule, 8091 disc, 97 local_par, 8 dir, 13063 glue, 348 
kern, 927 penalty, 63345 glyph, 62 attribute, 254 glue_spec, 22 attribute_list, 
1 write nodes
   avail lists: 2:93,3:116,4:20,5:245,6:11,7:8196,9:363,10:9,11:945
 25253 multiletter control sequences out of 65536+600000
 42 fonts using 18817439 bytes
 72i,5n,98p,401b,487s stack positions out of 10000i,1000n,20000p,200000b,200000s
<C:/Users/ME/AppData/Local/Programs/MiKTeX/fonts/truetype/public/amiri/amir
i-regular.ttf><C:/WINDOWS/Fonts/arial.ttf>
Output written on Test-Arba.pdf (2 pages, 61030 bytes).

PDF statistics: 23 PDF objects out of 1000 (max. 8388607)
 0 named destinations out of 1000 (max. 131072)
 1 words of extra memory for PDF output out of 10000 (max. 100000000)

**Comment by hpvd** [comment] 2023-04-08 19:27
not sure from which CnP the \par in the acrabic part is coming from...
removing it, there is no arabic part visible anymore...

**Comment by hpvd** [comment] 2023-04-08 19:30
If it works on your site, it's fine.
So something in my installation is messed up....

**Comment by hpvd** [comment] 2023-04-08 19:34
is this fine?
```
Package babel Info: Hyphen rules for 'arabic' set to \l@english
(babel)             (\language0). Reported on input line 10.
```

**Comment by jbezos** [comment] 2023-04-10 15:26
I’m closing this issue because it cannot be reproduced. As to the message, it’s harmless, I think, because Arabic is not hyphenated. It’s not shown in TeXLive, and perhaps there is misconfiguration in MikTeX (which is loading a `bblopts.cfg` almost 20 years old!).

**Closed by jbezos** 2023-04-10 15:26 UTC
